### PR TITLE
OS_dev -> master

### PR DESCRIPTION
**Pull request by derpycode**
This is a merge of some weathering tracer code into master, ready for creating a DOI for the paper.
The changes are relatively small and should mostly just impact ROKGEM and SEDGEM.
I have also re-formatted all the ROKGEM code with consistent indenting, and that will show up as 1000000000000 code changes :o)
Tests need only involve SEDGEM (/ROKGEM) and a repeat experiment just long enough to confirm that things still work at all and ideally the results are the same.

### CODE REVIEW

**Comment by DomHu** [comment]
I am running your LAB_11.EXAMPLE experiment for 200 years (i.e. using ROKGEM and SEDGEM with baseconfig: cgenie.eb_go_gs_ac_bg_sg_rg_gl._rwlma.BASES) on master and OS_dev. Will report back.

**Review by DomHu — APPROVED** [review]
Results of the experiments above are identical after 200 years.

**Comment by kanzakiy** [comment]
ran EXAMPLE.worbe2.RidgwellHargreaves1997_S36x36.SPIN2 for 200 yr with base-config genie.eb_go_gs_ac_bg_sg_rg.worbe2.BASE on master and OS_dev. 

Results are identical but noticed that rokgem results are a bit weirdly written in OS_dev:  OS, ALK and DIC etc. fluxes are mixed up in some results files (see attached).


   
comparison_rokgem_res1

comparison_rokgem_res2

**Comment by markus-adloff** [comment]
Thank you both, and great spot, kanzakiy! I needed Os fluxes in the ROKGEM global summary for testing purposes but didn't remove them properly. I removed them from the output and Alk, DIC, etc. should now have the correct values. Could you please pull Os_dev again and check?

**Review by kanzakiy — APPROVED** [review]
Ran again EXAMPLE.worbe2.RidgwellHargreaves1997_S36x36.SPIN2 for 200 yr with base-config genie.eb_go_gs_ac_bg_sg_rg.worbe2.BASE on updated OS_dev.

Results are identical to those on master!

**Pull request merged**
