### PR TITLE
Merge foram dev

### PR DESCRIPTION
**Pull request by derpycode**
I have replaced with original master copies, the user.mak, makefile.arc muffin environment settings files, and also the xml definition file, to try and ensure no future environment hick-ups as people pull new versions, and for the xml file, to ensure that ECOGEM behaves the same as before by default.
Left are various changes to ECOGEM .f90 files, that hopefully do not alter default ECOGEM behaviour -- this is what needs testing, i.e.
Does ECOGEM, across a range of different modern/paleo configs and different ecosystem structures, behave as before and the published experiment configurations still generate exactly the same results.

### CODE REVIEW

**Comment by derpycode** [comment]
Note that this branch -- MERGE_ForamDEV is Maria's ForamDEV branch, but with the files replaced as per described above. As long as the remaining FORTRAN changes do not upset ECOGEM default behaviour, then I think we are good to go on this (and merge into master).

**Comment by mariagrigoratou** [comment]
Hey, 

Jamie the 2.00000 printed values are the sigma parameter (i.e. grazing kernel's width). I added a PRINT*,ppsig_mat in ecogem.data (line 558) when I replaced pp_sig(:) with ppsig_mat to check if it works and never commented out :|.

**Comment by JamieDWilson** [comment]
Screen Shot 2019-11-15 at 13 11 01

I've run my main 2018 Paleocene experiment (same base/userconfig run from same restart) with master and this branch. The results are really different (see attached photo of mean size): biomass on this branch is way too low and number of size classes surviving is too low.

**Comment by mariagrigoratou** [comment]
Hello Jamie,

I had a look at the ecogem_data.f90 and zooplankton is defined to be carnivorous only (line 421, carnivory =1). I am very sorry for not checking that earlier, I complete forgot that I my last summer simulation was on testing group dynamics with different zooplankton diets.
I think that with the omnivory on (carnivory = 0) there will be no problem.

Again, I am very sorry for that.

Best,
Maria
________________________________

**Comment by JamieDWilson** [comment]
No worries, is the point of doing this! I'm re-running it with carnivory=0 (changed locally)...

**Comment by JamieDWilson** [comment]
eco2D_Plankton_C_Total in fields_ecogem_2d

Now very close agreement between branches (see above: differences are 10-3 mmol m-3).

So main changes needed so far:
1) remove print statement in ecogem_data.f90
2) set carnivory = 0 for zooplankton in ecogem_data.f90

**Comment by derpycode** [comment]
My expectation is that the biomass should not differ by more than ca. E-8 as a fraction of the original value. 'close' is not good enough -- it should be virtually indistinguishable, with differences fully accounted for by cumulative numerical errors arising from the finite machine precision.

**Pull request closed without merging**
