### PR TITLE
Dev gmd23

### PR DESCRIPTION
**Pull request by FannyMonteiro**
New code for EcoGEnIE 1.1 (Naidoo-Bagwell et al., GMD, 2023), which includes the implementation of phytoplankton functional groups diatoms, picophytoplankton and eukaryotes
     On branch DEV_GMD23
        new file:   genie-ecogem/data/input/3Diat_4ZP_PiEu.eco
        modified:   genie-ecogem/src/fortran/ecogem.f90
        modified:   genie-ecogem/src/fortran/ecogem_box.f90
        modified:   genie-ecogem/src/fortran/ecogem_data.f90
        modified:   genie-ecogem/src/fortran/ecogem_lib.f90
        modified:   genie-ecogem/src/fortran/initialise_ecogem.f90
        new file:   genie-main/configs/muffin.CBE.worjh2.BASESFeTDTLSi.Albani.config
        modified:   genie-main/src/xml-config/xml/definition.xml
        new folder: genie-userconfigs/PUBS/submitted/Naidoo-Bagwell_et_al.GMD.2023

### CODE REVIEW

**Comment by derpycode** [comment]
The code changes are basically limited to ECOGEM.
Please run some (ideally published) ECOGEM experiments you have previous carried out ... check that the results are the same under branch DEV_GMD23 as before.

**Comment by alexpohl** [comment]
Hi Andy,

I just launched two ecogem experiments from Cermeno et al., for 5000 years, on master and the new development branch.
I should be able to check the results on Monday.

– Alex

**Comment by geebes** [comment]
I have set two 1k year simulations off on master and Dev_gmd23...

**Comment by derpycode** [comment]
thanks!

**Comment by derpycode** [comment]
thanks!

**Comment by derpycode** [comment]
The circultion is very slightly different ... so any biogeochem differences could simply be due 
to that. hard to tell.


/andy

**Comment by derpycode** [comment]
Ran some worjh2 PO4-only experiments, for 1000 years from a non ECOGEM restart. The small ECOGEM differences seemed to be associated with the small differences in esp. sea-ice in the seasonal worjh2 config.
Unclear from everyone's testing whether there are any differences beyond those that might be expected from small differences in ocean circulation and sea-ice cover.
I am pushing the merge through.
People should simply be aware that we do not have 100% certainty that there are no changes at all in ECOGEM behavior as a result fo the code changes. If there are, they are very minor indeed.

**Pull request merged**
