### PR TITLE
_DEV_ECOGEM merge

### PR DESCRIPTION
**Pull request by derpycode**
Hey!
Time to merge in the ECOGEM changes ... adding sea-ice cover limitation to ECOGEM productivity, the carbon re-partitioning from POM to DOM fix, and the redistribution of export over the complete MLD.
There is a little additional C/P output, a temperature offset for T-dependent bio schemes (I cannot remember what this was for now ...), plus an extension for a deeper ocean grid but still retaining the old/default upper ocean layer structure. 
I guess the simplest check other than make testbiogem, would be to ensure taht you cna reproduce the ECOGEM experiment as detailed in Ward et al. [2018].

### CODE REVIEW

**Comment by DomHu** [comment]
I did the checkout. The files user.mak and makefile.arc were updated as well. So I had to change the netcdf settings. Should this be corrected, i.e. the 2 files should not be commited?

I am currently running the 2 experiments shown in Ben et al. (2018). Will let you know when finished.

**Comment by alexpohl** [comment]
make testbiogem ran fine. I just submitted the ecogenie SPINUP of Ward et al. (2018; see below) on both the master and _DEV_ECOGEM branches, and will compare the resulting ocean biogeochemitry using the python genie_basicdiags routines once the simulations done.

runmuffin.sh muffin.CBE.worlg4.BASESFeTDTL MS/wardetal.2018 wardetal.2018.ECOGEM.SPIN

**Comment by derpycode** [comment]
Files user.mak and makefile.arc are OK ... they should be unchanged as compared to master and still be the linux (Ubuntu) default settings.

**Comment by alexpohl** [comment]
On domino, I did not have to change them, as far as I’m concerned.
– Alex

**Comment by derpycode** [comment]
Your local user.mak and makefile.arc settings should be retained each time you checkout a new branch.
It might be -- Dom -- that you committed your user.mak and makefile.arc settings locally and that causes issues.
On my cluster account where I have to have different config settings, I get, in response to git status -uno:
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   genie-main/makefile
#       modified:   genie-main/user.mak
#
indicating that my local settings I did not commit. You retain these settings when checking out a different branch. Don't commit your local config settings locally.

**Comment by alexpohl** [comment]
Here are the results of the Ward et al. exp run on master and _DEV_ECOGEM: [https://cloud.u-bourgogne.fr:443/index.php/s/Y5HyX3cfWK9z4Ay](url)
Both seem to be ~identical.

**Comment by DomHu** [comment]
My ECOGEM experiment is still running. sprout is a little slower.

**Pull request merged**
