### PR TITLE
adding / updating CH4 cycle changes

### PR DESCRIPTION
**Pull request by derpycode**

### CODE REVIEW

**Comment by derpycode** [comment]
This ... could be a mess ... it is all probably OK ... :o)

**Comment by sevdevel** [comment]
I will do it tomorrow if you can wait that long!

**Comment by markusadloff** [comment]
I had a look through the changes and didn't see any obvious problems (but I'm not familiar with the atchem module). The code also passes the testbiogem on my almond account. Since the code comes with a lot of new config and userconfig files, are there experiments we could/should test to see if the different oxidation funtions work?

**Comment by ophiocordyceps** [comment]
Thanks for having a look.  The branch also passes testbiogem on domino.  I inadvertently committed the user configs (they will not be the final configs to be published with the paper).  Apologies for that.  But am currently re-running some of these older experiments with the branch as currently constituted and so far the CH4 diagnostics I've looked at match well.

**Pull request merged**
