### PR TITLE
_d13C -> master

### PR DESCRIPTION
**Pull request by derpycode**
An attempt to add some benthic foram d13C forward-proxy model output.
Not necessarily very good ... or even working ...
... but I'd like to merge before I forget what this branch was 'for' ...

TO-DO:
make testbiogem
repeat the start of any experiment involving d13C and check the results are exactly the same

### CODE REVIEW

**Comment by DomHu** [comment]
make testbiogem was okay
I just submitted an old experiment and will let it run for ~1000years

**Review by pamverv001 — APPROVED** [review]
Make testbiogem was okay
Ran a 5,000 year simulation with transient orbital forcing and an open carbon system on "master" and "_d13C" branches. Parameters CO2, CO2_13C, DIC_13C, and CaCO3_13C are all identical

**Comment by DomHu** [comment]
Same for me. Ran end-Permian experiment for 5000years including sedgem/omen-sed. The summary file 'biogem_year_04999_500_diag_GLOBAL_AVERAGE.res' is excatly the same and also the time-series files of biogem_series_ocn_DIC.res and biogem_series_ocn_DIC_13C.res

**Review by DomHu — COMMENTED** [review]
Same for me. Ran end-Permian experiment for 5000years including sedgem/omen-sed. The summary file 'biogem_year_04999_500_diag_GLOBAL_AVERAGE.res' is excatly the same and also the time-series files of biogem_series_ocn_DIC.res and biogem_series_ocn_DIC_13C.res

**Pull request merged**
